<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="11890" started-at="2023-08-04T05:47:42Z" finished-at="2023-08-04T05:47:54Z">
    <groups>
    </groups>
    <test name="CitrixLoginWithChrome" duration-ms="11890" started-at="2023-08-04T05:47:42Z" finished-at="2023-08-04T05:47:54Z">
      <class name="com.qa.test.webapplication.tests.CitrixResetPasswordURLTest">
        <test-method status="SKIP" signature="testCitrixResetPasswordLink(java.util.Map)[pri:0, instance:com.qa.test.webapplication.tests.CitrixResetPasswordURLTest@17bf99e]" name="testCitrixResetPasswordLink" duration-ms="0" started-at="2023-08-04T11:17:54Z" data-provider="smpData" finished-at="2023-08-04T11:17:54Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:111)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.qa.test.webapplication.tests.CitrixResetPasswordURLTest.getData(CitrixResetPasswordURLTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCitrixResetPasswordLink -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.qa.test.webapplication.tests.CitrixResetPasswordURLTest@17bf99e]" name="afterSuite" is-config="true" duration-ms="1012" started-at="2023-08-04T11:17:54Z" finished-at="2023-08-04T11:17:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.qa.test.webapplication.tests.CitrixResetPasswordURLTest -->
    </test> <!-- CitrixLoginWithChrome -->
  </suite> <!-- Suite -->
</testng-results>
